### ISSUE TITLE
Stiching after installing the mod

### ISSUE THREAD

**Issue by michelle1574** [AIDA64S/MTR-Station-Decoration-Addon#10]
![image](https://github.com/AIDA64S/MTR-Station-Decoration-Addon/assets/70703680/6893f996-d20c-43ad-9880-eab799a172b9)
[---- Minecraft Crash Report ----.txt](https://github.com/AIDA64S/MTR-Station-Decoration-Addon/files/15138670/----.Minecraft.Crash.Report.----.txt)

**Comment by AIDA64S** [comment]
Waiting for the release of MSD 1.3.5 (adapted to MTR4.0)
